const { PrismaClient } = require("@prisma/client");

const prisma = new PrismaClient();

const indonesianLiveTvChannels = [
  {
    id: "tv-tvri-nasional",
    title: "TVRI Nasional",
    description: "Televisi Republik Indonesia - Siaran TV nasional resmi 24 jam menyajikan berita, budaya, pendidikan, dan dokumenter Indonesia.",
    posterUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/TVRILogo2019.svg/960px-TVRILogo2019.svg.png",
    backdropUrl: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?w=1200&auto=format&fit=crop&q=80",
    videoUrl: "https://ott-balancer.tvri.go.id/live/eds/Nasional/hls/Nasional.m3u8",
    duration: 0,
    releaseYear: 2026,
    rating: 9.6,
    ageRating: "SU",
    quality: "Full HD",
    genres: ["News", "Drama"],
    cast: ["Presenter TVRI", "Direksi LPP TVRI"],
    directors: ["LPP TVRI"],
    subtitles: JSON.stringify([]),
    country: "Indonesia",
    language: "id",
    views: 345000,
    likes: 42000,
    isFeatured: true,
    isBanner: true,
    tier: "free",
    contentType: "livetv",
    seasons: JSON.stringify([]),
    createdAt: new Date().toISOString()
  },
  {
    id: "tv-trans7",
    title: "Trans7 Live",
    description: "Siaran langsung Trans7 menyajikan program hiburan terpopuler, On The Spot, Jejak Petualang, MotoGP, dan acara komedi.",
    posterUrl: "https://i.imgur.com/fAbGImS.png",
    backdropUrl: "https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37?w=1200&auto=format&fit=crop&q=80",
    videoUrl: "https://video.detik.com/trans7/smil:trans7.smil/index.m3u8",
    duration: 0,
    releaseYear: 2026,
    rating: 9.4,
    ageRating: "R13",
    quality: "Full HD",
    genres: ["Comedy", "Action"],
    cast: ["Host Trans7", "Tim Produksi Trans Corp"],
    directors: ["Trans Media"],
    subtitles: JSON.stringify([]),
    country: "Indonesia",
    language: "id",
    views: 289000,
    likes: 31000,
    isFeatured: true,
    isBanner: false,
    tier: "free",
    contentType: "livetv",
    seasons: JSON.stringify([]),
    createdAt: new Date().toISOString()
  },
  {
    id: "tv-transtv",
    title: "Trans TV Live",
    description: "Siaran langsung Trans TV menyajikan Bioskop Trans TV, Transmania, talkshow hits, dan program hiburan keluarga terbaik.",
    posterUrl: "https://upload.wikimedia.org/wikipedia/en/thumb/6/62/Trans_TV_2013.svg/960px-Trans_TV_2013.svg.png",
    backdropUrl: "https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?w=1200&auto=format&fit=crop&q=80",
    videoUrl: "https://video.detik.com/transtv/smil:transtv.smil/index.m3u8",
    duration: 0,
    releaseYear: 2026,
    rating: 9.3,
    ageRating: "R13",
    quality: "Full HD",
    genres: ["Action", "Comedy"],
    cast: ["Artis Trans TV", "Presenter Trans TV"],
    directors: ["Trans Media"],
    subtitles: JSON.stringify([]),
    country: "Indonesia",
    language: "id",
    views: 265000,
    likes: 29000,
    isFeatured: true,
    isBanner: false,
    tier: "free",
    contentType: "livetv",
    seasons: JSON.stringify([]),
    createdAt: new Date().toISOString()
  },
  {
    id: "tv-metrotv",
    title: "Metro TV Live",
    description: "Stasiun berita 24 jam terdepan di Indonesia menyajikan Primetime News, Kick Andy, Mata Najwa archives, & update terkini.",
    posterUrl: "https://i.imgur.com/QnU70NI.png",
    backdropUrl: "https://images.unsplash.com/photo-1585829365295-ab7cd400c167?w=1200&auto=format&fit=crop&q=80",
    videoUrl: "https://edge.medcom.id/live-edge/smil:metro.smil/playlist.m3u8",
    duration: 0,
    releaseYear: 2026,
    rating: 9.2,
    ageRating: "SU",
    quality: "Full HD",
    genres: ["News"],
    cast: ["Jurnalis Metro TV", "Anchor Newsroom"],
    directors: ["Media Group"],
    subtitles: JSON.stringify([]),
    country: "Indonesia",
    language: "id",
    views: 198000,
    likes: 24000,
    isFeatured: false,
    isBanner: false,
    tier: "free",
    contentType: "livetv",
    seasons: JSON.stringify([]),
    createdAt: new Date().toISOString()
  },
  {
    id: "tv-cnbc-id",
    title: "CNBC Indonesia Live",
    description: "Saluran TV berita ekonomi, pasar saham, investasi, perbankan, dan analisa bisnis nomor satu di Indonesia.",
    posterUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/51/CNBC_Indonesia_2025.svg/960px-CNBC_Indonesia_2025.svg.png",
    backdropUrl: "https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?w=1200&auto=format&fit=crop&q=80",
    videoUrl: "https://live.cnbcindonesia.com/livecnbc/smil:cnbctv.smil/playlist.m3u8",
    duration: 0,
    releaseYear: 2026,
    rating: 9.1,
    ageRating: "SU",
    quality: "Full HD",
    genres: ["News"],
    cast: ["Analis Ekonomi CNBC", "News Anchor CNBC"],
    directors: ["Trans Media & CNBC Universal"],
    subtitles: JSON.stringify([]),
    country: "Indonesia",
    language: "id",
    views: 175000,
    likes: 19500,
    isFeatured: false,
    isBanner: false,
    tier: "free",
    contentType: "livetv",
    seasons: JSON.stringify([]),
    createdAt: new Date().toISOString()
  },
  {
    id: "tv-rri-net",
    title: "RRI NET Live",
    description: "Radio Edukasi & Visual Televisi Radio Republik Indonesia menyajikan musik, berita daerah, dan siaran langsung budaya nusantara.",
    posterUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/RRI_NET_2023.svg/960px-RRI_NET_2023.svg.png",
    backdropUrl: "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80",
    videoUrl: "https://private-streaming.rri.go.id/memfs/6f77c7b5-feb2-4935-9f89-e7e9fca0a54a_output_0.m3u8",
    duration: 0,
    releaseYear: 2026,
    rating: 8.9,
    ageRating: "SU",
    quality: "Full HD",
    genres: ["News", "Animation"],
    cast: ["Penyiar RRI", "Tim RRI NET"],
    directors: ["LPP RRI"],
    subtitles: JSON.stringify([]),
    country: "Indonesia",
    language: "id",
    views: 95000,
    likes: 11200,
    isFeatured: false,
    isBanner: false,
    tier: "free",
    contentType: "livetv",
    seasons: JSON.stringify([]),
    createdAt: new Date().toISOString()
  },
  {
    id: "tv-indonesiana",
    title: "Indonesiana.TV",
    description: "Televisi Kebudayaan resmi Kementerian Pendidikan, Kebudayaan, Riset, dan Teknologi RI menyajikan ragam ekspresi budaya lokal.",
    posterUrl: "https://i.imgur.com/192wiS1.png",
    backdropUrl: "https://images.unsplash.com/photo-1533105079780-92b9be482077?w=1200&auto=format&fit=crop&q=80",
    videoUrl: "https://tvstreamcast.com/indonesiana.m3u8",
    duration: 0,
    releaseYear: 2026,
    rating: 9.0,
    ageRating: "SU",
    quality: "Full HD",
    genres: ["Drama", "Animation"],
    cast: ["Budayawan", "Seniman Indonesia"],
    directors: ["Kemendikbudristek RI"],
    subtitles: JSON.stringify([]),
    country: "Indonesia",
    language: "id",
    views: 112000,
    likes: 14300,
    isFeatured: false,
    isBanner: false,
    tier: "free",
    contentType: "livetv",
    seasons: JSON.stringify([]),
    createdAt: new Date().toISOString()
  },
  {
    id: "tv-tvri-jabar",
    title: "TVRI Jawa Barat",
    description: "Siaran langsung TVRI Stasiun Jawa Barat menyajikan berita daerah Parahyangan, seni Sunda, & informasi publik Jabar.",
    posterUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/TVRILogo2019.svg/960px-TVRILogo2019.svg.png",
    backdropUrl: "https://images.unsplash.com/photo-1506744038136-46273834b3fb?w=1200&auto=format&fit=crop&q=80",
    videoUrl: "https://ott-balancer.tvri.go.id/live/eds/Jabar/hls/Jabar.m3u8",
    duration: 0,
    releaseYear: 2026,
    rating: 8.8,
    ageRating: "SU",
    quality: "HD",
    genres: ["News"],
    cast: ["Presenter TVRI Jabar"],
    directors: ["TVRI Stasiun Jawa Barat"],
    subtitles: JSON.stringify([]),
    country: "Indonesia",
    language: "id",
    views: 82000,
    likes: 9800,
    isFeatured: false,
    isBanner: false,
    tier: "free",
    contentType: "livetv",
    seasons: JSON.stringify([]),
    createdAt: new Date().toISOString()
  },
  {
    id: "tv-tvri-jateng",
    title: "TVRI Jawa Tengah",
    description: "Siaran langsung TVRI Stasiun Jawa Tengah meliput berita wilayah Jateng, kebudayaan Jawa, dan program edukasi.",
    posterUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/e/eb/TVRILogo2019.svg/960px-TVRILogo2019.svg.png",
    backdropUrl: "https://images.unsplash.com/photo-1596402184320-417e7178b2cd?w=1200&auto=format&fit=crop&q=80",
    videoUrl: "https://ott-balancer.tvri.go.id/live/eds/Jateng/hls/Jateng.m3u8",
    duration: 0,
    releaseYear: 2026,
    rating: 8.8,
    ageRating: "SU",
    quality: "HD",
    genres: ["News"],
    cast: ["Presenter TVRI Jateng"],
    directors: ["TVRI Stasiun Jawa Tengah"],
    subtitles: JSON.stringify([]),
    country: "Indonesia",
    language: "id",
    views: 79000,
    likes: 8700,
    isFeatured: false,
    isBanner: false,
    tier: "free",
    contentType: "livetv",
    seasons: JSON.stringify([]),
    createdAt: new Date().toISOString()
  },
  {
    id: "tv-daaitv",
    title: "DAAI TV Indonesia",
    description: "Televisi Kemanusiaan menyajikan drama inspiratif kehidupan, acara anak edukatif, berita positif, dan dokumenter lingkungan.",
    posterUrl: "https://i.imgur.com/YC7JCHo.png",
    backdropUrl: "https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=1200&auto=format&fit=crop&q=80",
    videoUrl: "https://pull.daaiplus.com/live-DAAIPLUS/live-DAAIPLUS_HD.m3u8",
    duration: 0,
    releaseYear: 2026,
    rating: 9.2,
    ageRating: "SU",
    quality: "Full HD",
    genres: ["Drama", "Animation"],
    cast: ["Relawan DAAI", "Presenter DAAI TV"],
    directors: ["DAAI TV Indonesia"],
    subtitles: JSON.stringify([]),
    country: "Indonesia",
    language: "id",
    views: 121000,
    likes: 15600,
    isFeatured: false,
    isBanner: false,
    tier: "free",
    contentType: "livetv",
    seasons: JSON.stringify([]),
    createdAt: new Date().toISOString()
  }
];

async function seedIndonesianLiveTv() {
  console.log("Seeding Indonesian Local TV Channels directly to PostgreSQL / Database...");
  for (const channel of indonesianLiveTvChannels) {
    await prisma.movie.upsert({
      where: { id: channel.id },
      update: channel,
      create: channel
    });
    console.log(`  ✔ Seeded channel: ${channel.title}`);
  }
  console.log("🎉 Successfully seeded 10 Legal Indonesian Local TV Channels into Database!");
}

seedIndonesianLiveTv()
  .catch((e) => {
    console.error("❌ Error seeding Indonesian Live TV channels:", e);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
